env:
  - name: LOG_LEVEL
    value: info
  - name: HOST
    value: 0.0.0.0
  - name: LLM_URLS
    value: '["http://cpu-inference-service-predictor/v1"]'
  - name: DB_PROVIDERS
    valueFrom:
      secretKeyRef:
        name: rag-llm-frontend-rag-llm-demo-ui
        key: db_providers

dbProvidersSecret:
  vault:
    - key: mssql
      field: sapassword
    - key: pgvector
      field: user
    - key: pgvector
      field: password
    - key: pgvector
      field: db
    - key: elastic
      field: user
    - key: elastic
      field: password
  providers:
    - type: qdrant
      collection: docs
      url: http://qdrant-service:6333
      embedding_model: sentence-transformers/all-mpnet-base-v2
    - type: redis
      index: docs
      url: redis://redis-service:6379
      embedding_model: sentence-transformers/all-mpnet-base-v2
    - type: elastic
      index: docs
      url: http://elastic-service:9200
      user: "{{ .elastic_user }}"
      password: "{{ .elastic_password }}"
      embedding_model: sentence-transformers/all-mpnet-base-v2
    - type: pgvector
      collection: docs
      url: >-
        postgresql+psycopg://{{ .pgvector_user }}:{{ .pgvector_password }}@pgvector-service:5432/{{ .pgvector_db }}
      embedding_model: sentence-transformers/all-mpnet-base-v2
    - type: mssql
      table: docs
      connection_string: >-
        Driver={ODBC Driver 18 for SQL Server};
        Server=mssql-service,1433;
        Database=embeddings;
        UID=sa;
        PWD={{ .mssql_sapassword }};
        TrustServerCertificate=yes;
        Encrypt=no;
      embedding_model: sentence-transformers/all-mpnet-base-v2
