providers:
  qdrant:
    enabled: true
  mssql:
    enabled: true

vectorEmbedJob:
  repoSources:
    - repo: https://github.com/validatedpatterns/docs.git
      globs:
        - "**/*.md"
        - "**/*.adoc"
  webSources: []
  chunking:
    size: 4096
