clusterGroup:
  name: prod

  namespaces:
    - rag-llm-no-gpu
    - vault
    - golang-external-secrets
    - redhat-ods-operator:
        operatorGroup: true
        targetNamespaces: []
    - openshift-serverless:
        operatorGroup: true
        targetNamespaces: []

  subscriptions:
    serverless:
      name: serverless-operator
      namespace: openshift-serverless
    servicemesh:
      name: servicemeshoperator
      namespace: openshift-operators
    rhoai:
      name: rhods-operator
      namespace: redhat-ods-operator

  applications:
    golang-external-secrets:
      name: golang-external-secrets
      namespace: golang-external-secrets
      chart: golang-external-secrets
      chartVersion: 0.1.*

    vault:
      name: vault
      namespace: vault
      chart: hashicorp-vault
      chartVersion: 0.1.*

    rag-llm-frontend:
      name: rag-llm-frontend
      namespace: rag-llm-no-gpu
      repoURL: https://github.com/validatedpatterns-sandbox/rag-llm-demo-ui
      chartVersion: main
      path: helm
      extraValueFiles:
        - $patternref/overrides/rag-llm-frontend-values.yaml

    vector-db:
      name: vector-db
      namespace: rag-llm-no-gpu
      chart: vector-db
      chartVersion: 0.1.*
      extraValueFiles:
        - $patternref/overrides/vector-db-values.yaml

    llm-inference-service:
      name: llm-inference-service
      namespace: rag-llm-no-gpu
      chart: llm-inference-service
      chartVersion: 0.2.*
      extraValueFiles:
        - $patternref/overrides/llm-inference-service-values.yaml
